version: '2.3'
services:
  mockgen:
    build:
      context: .
      dockerfile: Dockerfile.mockgen
      args:
        - http_proxy
        - https_proxy
    environment:
      - http_proxy
      - https_proxy
    volumes:
      - .:/workspace
    working_dir: /workspace
    command:
      - /bin/sh
      - -c
      - |
        set -e
        go get -d google.golang.org/genproto/googleapis/devtools/cloudbuild/v1
        mockgen \
          -package=testutil \
          -destination=testutil/cloudbuild_grpc_mockgen.go \
          google.golang.org/genproto/googleapis/devtools/cloudbuild/v1 \
          CloudBuildServer
