name: Release ikedam/cloudbuild
on:
  push:
    tags:
      - v*
env:
  DOCKERHUB_REPOSITORY: ikedam/cloudbuild
jobs:
  release-github:
    name: Release to Github
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Required for changelog
      - name: Unshallow
        run: git fetch --prune --unshallow
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release-docker:
    name: Publish to dockerhub and github packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t cloudbuild \
            --build-arg VERSION=${GITHUB_REF##*/v} \
            --build-arg COMMIT=${GITHUB_SHA} \
            .
      - name: Login
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" \
            | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
          echo "${{ secrets.GITHUB_TOKEN }}" \
            | docker login docker.pkg.github.com -u "${GITHUB_REPOSITORY%/*}" --password-stdin
      - name: Deploy
        run: |
          TAG=${GITHUB_REF##*/v}
          docker tag cloudbuild "${DOCKERHUB_REPOSITORY}:${TAG}"
          docker tag cloudbuild "${DOCKERHUB_REPOSITORY}:latest"
          docker tag cloudbuild "docker.pkg.github.com/${GITHUB_REPOSITORY}/cloudbuild:${TAG}"
          docker tag cloudbuild "docker.pkg.github.com/${GITHUB_REPOSITORY}/cloudbuild:latest"
          docker push "${DOCKERHUB_REPOSITORY}:${TAG}"
          docker push "${DOCKERHUB_REPOSITORY}:latest"
          docker push "docker.pkg.github.com/${GITHUB_REPOSITORY}/cloudbuild:${TAG}"
          docker push "docker.pkg.github.com/${GITHUB_REPOSITORY}/cloudbuild:latest"
      # Cannot update the docker hub description with dockerhub token.
      # It requires the actual password (as it's documented in dockerhub-description action).
      # It's not a good idea to store the password and I don't activate this.
      # - name: Docker Hub Description
      #   uses: peter-evans/dockerhub-description@v2.1.0
      #   env:
      #     DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      #     DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
